
name: CI

on:
  workflow-dispatch:

jobs:
  time-cgol:
    name: Time CGOL step() function
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Set up nox
        run: uv tool install nox

      - name: Run timer
        run: uv tool run nox -s time